Repository blackjack4494/youtube-dlc, pull requests merged in 2020-09, with the labels that each got.

#34 Twitch fix
  youtube_dlc/extractor/twitch.py
Labels: tested

#29 [wdr] fix subtitle extraction
  youtube_dlc/extractor/wdr.py
Labels: high, tested

#16 Abc
  youtube_dlc/extractor/abc.py
Labels: high

#28 Mkvthumbnail
  youtube_dlc/postprocessor/embedthumbnail.py
Labels: medium

#22 Ondemandkorea
  youtube_dlc/extractor/ondemandkorea.py
Labels: medium

#57 [ard.py] add playlist support
  youtube_dlc/extractor/ard.py
Labels: low

#59 [magentamusik360] Add new extractor
  youtube_dlc/extractor/extractors.py
  youtube_dlc/extractor/magentamusik360.py
Labels: low

#15 [rutv] Fix JSON URL (closes #26333)
  youtube_dlc/extractor/rutv.py
Labels: low

#68 [gdrive] Fix/google drive cookie issue
  youtube_dlc/extractor/googledrive.py
Labels: low

#63 vrt
  youtube_dlc/extractor/vrt.py
Labels: low

#18 [rai] Fix extraction for recent raiplay.it updates
  youtube_dlc/extractor/rai.py
Labels: medium

#69 [Viki] subtitles, formats
  youtube_dlc/extractor/viki.py
Labels: medium

#17 [MyVideoGe] add new extractor
  youtube_dlc/extractor/extractors.py
  youtube_dlc/extractor/myvideoge.py
Labels: low

#72 [bitchute] Fix error for geoblocking
  youtube_dlc/extractor/bitchute.py
Labels: low

#21 Alura
  youtube_dlc/extractor/alura.py
  youtube_dlc/extractor/extractors.py
Labels: low

#73 [duboku] new extractor
  youtube_dlc/extractor/duboku.py
  youtube_dlc/extractor/extractors.py
Labels: low

#62 Tiktok
  youtube_dlc/extractor/extractors.py
  youtube_dlc/extractor/tiktok.py
Labels: low

#116 [Core] Added --remux-video option
  README.md
  devscripts/fish-completion.py
  devscripts/zsh-completion.in
  youtube_dlc/__init__.py
  youtube_dlc/options.py
  youtube_dlc/postprocessor/__init__.py
  youtube_dlc/postprocessor/ffmpeg.py
Labels: medium

#149 Added regex for ABC.com site.
  youtube_dlc/extractor/go.py
Labels: check needed, medium
